import numpy as np
import scipy.constants

# --- Constants ---
# Planck's constant (J*Hz^-1)
H_PLANCK = scipy.constants.h
# Speed of light (m/s) - not directly used for f if f is given, but good for context
C_LIGHT = scipy.constants.c
# Typical optical frequency for C-band (Hz) e.g., 193.1 THz
OPTICAL_FREQ_HZ = 193.1e12 # Hz (corresponding to approx. 1550 nm)


def apply_fiber_loss(signal: np.ndarray, fiber_length_km: float, attenuation_db_per_km: float) -> np.ndarray:
    """
    Applies fiber attenuation to an optical signal.

    Args:
        signal: NumPy array of complex symbols.
        fiber_length_km: Length of the fiber in kilometers.
        attenuation_db_per_km: Attenuation coefficient of the fiber in dB/km.

    Returns:
        NumPy array of complex symbols after attenuation.
    """
    if not isinstance(signal, np.ndarray):
        raise TypeError("Signal must be a NumPy array.")
    if not (isinstance(fiber_length_km, (int, float)) and fiber_length_km >= 0):
        raise ValueError("Fiber length must be a non-negative number.")
    if not (isinstance(attenuation_db_per_km, (int, float)) and attenuation_db_per_km >= 0):
        raise ValueError("Attenuation (dB/km) must be a non-negative number.")

    total_loss_db = fiber_length_km * attenuation_db_per_km
    loss_linear = 10**(-total_loss_db / 10)
    return signal * np.sqrt(loss_linear) # Apply to amplitude (sqrt for power)

def apply_edfa_gain(signal: np.ndarray, gain_db: float) -> np.ndarray:
    """
    Applies EDFA gain to an optical signal.

    Args:
        signal: NumPy array of complex symbols.
        gain_db: Gain of the EDFA in dB.

    Returns:
        NumPy array of complex symbols after amplification.
    """
    if not isinstance(signal, np.ndarray):
        raise TypeError("Signal must be a NumPy array.")
    if not isinstance(gain_db, (int, float)):
        raise ValueError("Gain (dB) must be a number.")

    gain_linear = 10**(gain_db / 10)
    return signal * np.sqrt(gain_linear) # Apply to amplitude (sqrt for power)

def add_ase_noise(signal: np.ndarray, edfa_gain_db: float, edfa_noise_figure_db: float,
                  symbol_rate_gbd: float, num_channels: int = 1) -> np.ndarray:
    """
    Adds Amplified Spontaneous Emission (ASE) noise to the signal.
    This model assumes ASE noise is generated by an EDFA and added to a single polarization signal.

    Args:
        signal: Input signal (NumPy array of complex symbols).
        edfa_gain_db: Gain of the EDFA in dB.
        edfa_noise_figure_db: Noise figure of the EDFA in dB.
        symbol_rate_gbd: Symbol rate in GigaBaud (e.g., 32).
        num_channels: Number of WDM channels (default 1). Currently, this primarily
                      influences understanding of B_noise context but not directly used
                      if symbol_rate_gbd defines the noise bandwidth for the channel of interest.

    Returns:
        Signal with added ASE noise.
    """
    if not isinstance(signal, np.ndarray):
        raise TypeError("Signal must be a NumPy array.")
    if not isinstance(edfa_gain_db, (int, float)):
        raise ValueError("EDFA gain (dB) must be a number.")
    if not (isinstance(edfa_noise_figure_db, (int, float)) and edfa_noise_figure_db >= 0):
        raise ValueError("EDFA Noise Figure (dB) must be a non-negative number.")
    if not (isinstance(symbol_rate_gbd, (int, float)) and symbol_rate_gbd > 0):
        raise ValueError("Symbol rate (GBd) must be a positive number.")

    # 1. Convert EDFA gain (G) and noise figure (NF) from dB to linear scale.
    gain_linear = 10**(edfa_gain_db / 10)
    noise_figure_linear = 10**(edfa_noise_figure_db / 10)

    # 2. Photon energy (h*f)
    photon_energy = H_PLANCK * OPTICAL_FREQ_HZ

    # 3. ASE power spectral density (PSD) on one polarization for one amplifier.
    # Using (G - 1) * NF * h * f for ASE generated *within* the amplifier.
    # n_sp = (NF / 2) if NF definition includes input noise. Or n_sp = NF if NF is for internal noise.
    # Standard definition: P_ase = (G-1) * NF * h * f * B_noise (for one pol)
    # where NF is the noise figure. Some texts use n_sp (spontaneous emission factor)
    # where NF_lin = 2*n_sp for high gain EDFAs if signal is shot noise limited at input.
    # Or simply, F = P_noise_out / (G * P_noise_in_ideal).
    # P_ASE_density_one_pol = (gain_linear - 1) * noise_figure_linear * photon_energy # This is N_ase_one_pol
    # A common alternative: P_ASE_density_one_pol = gain_linear * noise_figure_linear * photon_energy / 2 (if NF defined wrt input vacuum noise on 2 pols)
    # Let's stick to the (G-1) * NF * h * f definition as specified for one polarization ASE power.
    # This corresponds to P_ASE = (G-1) * n_sp * h * nu * B_noise where n_sp = NF / 2 for an ideal amplifier limited by quantum noise.
    # However, the problem states N_ase_one_pol = (G - 1) * NF * h * f.
    # This implies NF is not the "ideal quantum limited NF" but the actual device NF.
    n_ase_psd_one_pol = (gain_linear - 1) * noise_figure_linear * photon_energy

    # 4. Noise bandwidth (B_noise) is effectively the symbol rate.
    b_noise_hz = symbol_rate_gbd * 1e9  # Convert Gbd to Hz

    # 5. Total ASE noise power in the signal bandwidth for one polarization.
    p_ase_one_pol = n_ase_psd_one_pol * b_noise_hz

    # 6. Noise variance sigma_sq_ase_one_pol = P_ase_one_pol.
    # This is the total power for the complex noise n = n_re + j*n_im.
    # So, E[|n|^2] = E[n_re^2] + E[n_im^2] = p_ase_one_pol.
    # Assuming n_re and n_im are IID, E[n_re^2] = E[n_im^2] = p_ase_one_pol / 2.
    # The variance for np.random.normal is sigma^2, so we need sqrt(variance) for std dev.
    variance_per_quadrature = p_ase_one_pol / 2.0

    if variance_per_quadrature < 0:
        # This can happen if G < 1 (i.e., edfa_gain_db is negative)
        # In such a case, (G-1) is negative. Physically, an attenuator doesn't add this kind of noise.
        # We should either raise an error or return signal unchanged.
        # For now, let's assume gain_db implies an amplifying stage.
        # If gain_linear is very close to 1, this can be near zero.
        print(f"Warning: ASE noise variance per quadrature is negative ({variance_per_quadrature}). "
              f"This might be due to gain < 1 (Gain_linear: {gain_linear}). Clamping to zero.")
        variance_per_quadrature = 0.0


    # 7. Generate complex Gaussian noise.
    # The `scale` parameter for np.random.normal is the standard deviation (sigma), not variance.
    std_dev_per_quadrature = np.sqrt(variance_per_quadrature)

    noise_real = np.random.normal(0, std_dev_per_quadrature, signal.shape)
    noise_imag = np.random.normal(0, std_dev_per_quadrature, signal.shape)

    complex_noise = noise_real + 1j * noise_imag

    return signal + complex_noise


def propagate_through_spans(signal: np.ndarray, num_spans: int,
                            fiber_length_km: float, attenuation_db_per_km: float,
                            edfa_gain_db: float, edfa_noise_figure_db: float,
                            symbol_rate_gbd: float, num_channels: int = 1) -> np.ndarray:
    """
    Propagates an optical signal through multiple fiber spans, each followed by an EDFA.

    Args:
        signal: Input signal (NumPy array of complex symbols).
        num_spans: Number of fiber spans.
        fiber_length_km: Length of each fiber span in km.
        attenuation_db_per_km: Attenuation coefficient of the fiber in dB/km.
        edfa_gain_db: Gain of each EDFA in dB. Typically set to compensate for span loss.
        edfa_noise_figure_db: Noise figure of each EDFA in dB.
        symbol_rate_gbd: Symbol rate in GigaBaud.
        num_channels: Number of WDM channels (default 1).

    Returns:
        The signal after propagation through all spans.
    """
    if not isinstance(signal, np.ndarray):
        raise TypeError("Signal must be a NumPy array.")
    if not (isinstance(num_spans, int) and num_spans >= 0):
        raise ValueError("Number of spans must be a non-negative integer.")
    # Other parameters will be validated by the called functions.

    current_signal = signal.copy() # Work on a copy

    for span_idx in range(num_spans):
        # 1. Apply fiber loss
        current_signal = apply_fiber_loss(current_signal, fiber_length_km, attenuation_db_per_km)

        # 2. Apply EDFA gain
        current_signal = apply_edfa_gain(current_signal, edfa_gain_db)

        # 3. Add ASE noise from the EDFA
        current_signal = add_ase_noise(current_signal, edfa_gain_db, edfa_noise_figure_db,
                                       symbol_rate_gbd, num_channels)

    return current_signal

if __name__ == '__main__':
    # --- Example Parameters ---
    num_symbols_example = 10000
    # For QPSK, average power is 1 if symbols are like (1+1j)/sqrt(2)
    test_signal_power_avg = 1.0
    # Create a sample signal with average power of test_signal_power_avg
    # A QPSK signal would have specific points, but for testing channel, random complex numbers are fine.
    # Let's make it so E[|s|^2] = test_signal_power_avg
    # If s = x + jy, and x, y are from N(0, sigma_s^2), then E[|s|^2] = 2*sigma_s^2
    # So, sigma_s = sqrt(test_signal_power_avg / 2)
    sigma_s = np.sqrt(test_signal_power_avg / 2.0)
    example_signal = np.random.normal(0, sigma_s, num_symbols_example) + \
                     1j * np.random.normal(0, sigma_s, num_symbols_example)

    print(f"Initial signal average power: {np.mean(np.abs(example_signal)**2):.4f}")

    # Fiber parameters
    fiber_span_length_km_ex = 80.0  # km
    fiber_attenuation_db_per_km_ex = 0.2  # dB/km
    span_loss_db = fiber_span_length_km_ex * fiber_attenuation_db_per_km_ex # Should be 16 dB

    # EDFA parameters
    # Typically, EDFA gain compensates for the span loss
    edfa_gain_db_ex = span_loss_db # e.g., 16 dB to compensate for 80km * 0.2 dB/km
    edfa_noise_figure_db_ex = 5.0  # dB

    # System parameters
    symbol_rate_gbd_ex = 32.0  # GBd

    # --- Test apply_fiber_loss ---
    signal_after_loss = apply_fiber_loss(example_signal, fiber_span_length_km_ex, fiber_attenuation_db_per_km_ex)
    expected_power_after_loss = test_signal_power_avg * (10**(-span_loss_db / 10))
    print(f"Span loss: {span_loss_db:.2f} dB")
    print(f"Signal power after loss: {np.mean(np.abs(signal_after_loss)**2):.4f} (Expected: {expected_power_after_loss:.4f})")

    # --- Test apply_edfa_gain ---
    # Use signal_after_loss as input to EDFA
    signal_after_gain = apply_edfa_gain(signal_after_loss, edfa_gain_db_ex)
    # Expected power is close to initial power if gain compensates loss
    print(f"EDFA gain: {edfa_gain_db_ex:.2f} dB")
    print(f"Signal power after gain (no ASE): {np.mean(np.abs(signal_after_gain)**2):.4f} (Expected: ~{test_signal_power_avg:.4f})")

    # --- Test add_ase_noise ---
    # For testing ASE, let's use a signal that has just been amplified (so G is known)
    # We use signal_after_gain which has power ~test_signal_power_avg
    signal_with_ase = add_ase_noise(signal_after_gain, edfa_gain_db_ex, edfa_noise_figure_db_ex, symbol_rate_gbd_ex)

    # Calculate expected ASE power for one amplifier
    gain_lin = 10**(edfa_gain_db_ex / 10)
    nf_lin = 10**(edfa_noise_figure_db_ex / 10)
    photon_energy = H_PLANCK * OPTICAL_FREQ_HZ
    b_noise = symbol_rate_gbd_ex * 1e9
    expected_p_ase_one_pol = (gain_lin - 1) * nf_lin * photon_energy * b_noise

    # Power of signal_with_ase = Power of signal_after_gain + Expected P_ASE
    expected_total_power_after_ase = np.mean(np.abs(signal_after_gain)**2) + expected_p_ase_one_pol
    actual_total_power_after_ase = np.mean(np.abs(signal_with_ase)**2)
    # The noise added is random, so actual power will fluctuate. For large num_symbols_example, it should be close.
    print(f"Expected P_ASE (one EDFA, one pol): {expected_p_ase_one_pol:.4e}")
    print(f"Signal power after gain + ASE: {actual_total_power_after_ase:.4f} (Expected: {expected_total_power_after_ase:.4f})")
    print(f"OSNR estimate (P_signal / P_ASE_in_signal_BW): "
          f"{(np.mean(np.abs(signal_after_gain)**2) / expected_p_ase_one_pol):.2f} "
          f"({10*np.log10(np.mean(np.abs(signal_after_gain)**2) / expected_p_ase_one_pol):.2f} dB)")


    # --- Test propagate_through_spans ---
    num_spans_ex = 5
    print(f"\n--- Propagating through {num_spans_ex} spans ---")
    # Reset EDFA gain to exactly compensate typical span loss for multi-span
    edfa_gain_for_multi_span_db = fiber_span_length_km_ex * fiber_attenuation_db_per_km_ex

    signal_out_multi_span = propagate_through_spans(
        example_signal,
        num_spans=num_spans_ex,
        fiber_length_km=fiber_span_length_km_ex,
        attenuation_db_per_km=fiber_attenuation_db_per_km_ex,
        edfa_gain_db=edfa_gain_for_multi_span_db,
        edfa_noise_figure_db=edfa_noise_figure_db_ex,
        symbol_rate_gbd=symbol_rate_gbd_ex
    )

    # In a multi-span system where gain compensates loss, signal power should be roughly constant.
    # Noise accumulates. Total accumulated ASE power after N spans is roughly N * P_ase_one_pol (if G restores power to original level each time)
    # P_signal_out_multi_span is expected to be around test_signal_power_avg
    # P_ASE_total_multi_span is expected to be around num_spans_ex * expected_p_ase_one_pol

    p_signal_out_multi_span = np.mean(np.abs(example_signal)**2) # Assuming signal part remains at this level
    p_ase_total_multi_span_expected = num_spans_ex * expected_p_ase_one_pol

    print(f"Signal power after {num_spans_ex} spans: {np.mean(np.abs(signal_out_multi_span)**2):.4f}")
    print(f"(Expected signal component power: {p_signal_out_multi_span:.4f})")
    print(f"(Expected total ASE component power: {p_ase_total_multi_span_expected:.4e})")
    print(f"Final OSNR estimate after {num_spans_ex} spans: "
          f"{(p_signal_out_multi_span / p_ase_total_multi_span_expected):.2f} "
          f"({10*np.log10(p_signal_out_multi_span / p_ase_total_multi_span_expected):.2f} dB)")

    print("\n--- Testing Error Handling ---")
    try:
        apply_fiber_loss(example_signal, -10, 0.2)
    except ValueError as e:
        print(f"Caught expected error for apply_fiber_loss: {e}")
    try:
        add_ase_noise(example_signal, 16, -5, 32)
    except ValueError as e:
        print(f"Caught expected error for add_ase_noise: {e}")
    try:
        propagate_through_spans(example_signal, -1, 80, 0.2, 16, 5, 32)
    except ValueError as e:
        print(f"Caught expected error for propagate_through_spans: {e}")
    # Test ASE with gain < 1dB (results in (G-1) < 0)
    print("Testing ASE with gain_db = 0 (G_lin = 1):")
    add_ase_noise(example_signal, 0, edfa_noise_figure_db_ex, symbol_rate_gbd_ex)
    print("Testing ASE with gain_db = -2 (G_lin < 1):")
    add_ase_noise(example_signal, -2, edfa_noise_figure_db_ex, symbol_rate_gbd_ex)


    print("\nModule functionality tests complete.")
